const reductions = {
   "TapDmg": {
      "Clan Ship": 0,
      "Shadow Clone": 0.6,
      "Heavenly Strike": 1,
      "Pet": 1,
      "Dagger": 1,
      "Gold Gun": 0.45,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "TapDmgFromHelpers": {
      "Clan Ship": 0,
      "Shadow Clone": 1,
      "Heavenly Strike": 1,
      "Pet": 1,
      "Dagger": 1,
      "Gold Gun": 1,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "BurstSkillBoost": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 1,
      "Pet": 0,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "FairyGold": {
      "Clan Ship": null,
      "Shadow Clone": null,
      "Heavenly Strike": null,
      "Pet": null,
      "Dagger": null,
      "Gold Gun": null,
      "Fairy": 1,
      "HoG": 0,
      "Chesterson": 0
   },
   "HeavyStrikes": {
      "Clan Ship": 1,
      "Shadow Clone": 1,
      "Heavenly Strike": 1,
      "Pet": 1,
      "Dagger": 1,
      "Gold Gun": 1,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "BurstSkillMana": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 0,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "FairyChance": {
      "Clan Ship": null,
      "Shadow Clone": null,
      "Heavenly Strike": null,
      "Pet": null,
      "Dagger": null,
      "Gold Gun": null,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "Frenzy": {
      "Clan Ship": 0,
      "Shadow Clone": 0.6,
      "Heavenly Strike": 1,
      "Pet": 1,
      "Dagger": 1,
      "Gold Gun": 0.45,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "BurstDamageMultiCastSkill": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 1,
      "Pet": 0,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "TwilightGathering": {
      "Clan Ship": 0,
      "Shadow Clone": 1,
      "Heavenly Strike": 1,
      "Pet": 0,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "TwilightBell": {
      "Clan Ship": 0,
      "Shadow Clone": 1,
      "Heavenly Strike": 1,
      "Pet": 0,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "TwilightGatheringMultiCastSkill": {
      "Clan Ship": 0,
      "Shadow Clone": 1,
      "Heavenly Strike": 1,
      "Pet": 0,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "PetDmg": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 1,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "FireTapSkillBoost": {
      "Clan Ship": 0,
      "Shadow Clone": 0.6,
      "Heavenly Strike": 1,
      "Pet": 1,
      "Dagger": 1,
      "Gold Gun": 0.45,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "PetGoldQTE": {
      "Clan Ship": null,
      "Shadow Clone": null,
      "Heavenly Strike": null,
      "Pet": null,
      "Dagger": null,
      "Gold Gun": null,
      "Fairy": 0,
      "HoG": 1,
      "Chesterson": 0
   },
   "PetEquipmentBoost": {
      "Clan Ship": 1,
      "Shadow Clone": 1,
      "Heavenly Strike": 0,
      "Pet": 1,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "PetBonusBoost": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 1,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "PetQTE": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 1,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "CombatTechniques": {
      "Clan Ship": 4,
      "Shadow Clone": 3.6,
      "Heavenly Strike": 3.75,
      "Pet": 3.5,
      "Dagger": 3.65,
      "Gold Gun": 3.9,
      "Fairy": 1,
      "HoG": 1,
      "Chesterson": 1
   },
   "TapBoostMultiCastSkill": {
      "Clan Ship": 0,
      "Shadow Clone": 0.6,
      "Heavenly Strike": 1,
      "Pet": 1,
      "Dagger": 1,
      "Gold Gun": 0.45,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "BossDmgQTE": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 1,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "DualPetBoost": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 1,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "SummonerAutoTap": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 1,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "DualPetMultiCast": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 1,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "AllHelperDmg": {
      "Clan Ship": 1,
      "Shadow Clone": 0.6,
      "Heavenly Strike": 0.5,
      "Pet": 0.5,
      "Dagger": 0.5,
      "Gold Gun": 0.9,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "HelperBoost": {
      "Clan Ship": 107,
      "Shadow Clone": 108.6,
      "Heavenly Strike": 111,
      "Pet": 111,
      "Dagger": 111,
      "Gold Gun": 114.8,
      "Fairy": 83,
      "HoG": 79,
      "Chesterson": 78
   },
   "HelperDmgSkillBoost": {
      "Clan Ship": 1,
      "Shadow Clone": 0.6,
      "Heavenly Strike": 0.5,
      "Pet": 0.5,
      "Dagger": 0.5,
      "Gold Gun": 0.9,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "ClanShipDmg": {
      "Clan Ship": 1,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 0,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "ClanQTE": {
      "Clan Ship": 1,
      "Shadow Clone": 0.6,
      "Heavenly Strike": 0.5,
      "Pet": 0.5,
      "Dagger": 0.5,
      "Gold Gun": 0.9,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "HelperInspiredWeaken": {
      "Clan Ship": 1,
      "Shadow Clone": 0.6,
      "Heavenly Strike": 0.5,
      "Pet": 0.5,
      "Dagger": 0.5,
      "Gold Gun": 0.9,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "ClanShipStun": {
      "Clan Ship": 1,
      "Shadow Clone": 1,
      "Heavenly Strike": 1,
      "Pet": 1,
      "Dagger": 1,
      "Gold Gun": 1,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "HelperDmgQTE": {
      "Clan Ship": 1,
      "Shadow Clone": 0.6,
      "Heavenly Strike": 0.5,
      "Pet": 0.5,
      "Dagger": 0.5,
      "Gold Gun": 0.9,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "HelperBoostMultiCastSkill": {
      "Clan Ship": 1,
      "Shadow Clone": 0.6,
      "Heavenly Strike": 0.5,
      "Pet": 0.5,
      "Dagger": 0.5,
      "Gold Gun": 0.9,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "ClanShipVoltage": {
      "Clan Ship": 1,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 0,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "ClanShipVoltageMultiCastSkill": {
      "Clan Ship": 1,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 0,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "CloneDmg": {
      "Clan Ship": 0,
      "Shadow Clone": 1,
      "Heavenly Strike": 0,
      "Pet": 0,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "MPCapacityBoost": {
      "Clan Ship": 0.05,
      "Shadow Clone": 0.05,
      "Heavenly Strike": 0.05,
      "Pet": 0.05,
      "Dagger": 0.05,
      "Gold Gun": 0.05,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "CloneSkillBoost": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 0,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "ManaStealSkillBoost": {
      "Clan Ship": 0.05,
      "Shadow Clone": 0.05,
      "Heavenly Strike": 0.05,
      "Pet": 0.05,
      "Dagger": 0.05,
      "Gold Gun": 0.05,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "ManaMonster": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 0,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "BossTimer": {
      "Clan Ship": 2.5,
      "Shadow Clone": 3.8,
      "Heavenly Strike": 3.5,
      "Pet": 3.2,
      "Dagger": 3.25,
      "Gold Gun": 1.95,
      "Fairy": 0.6,
      "HoG": 0.6,
      "Chesterson": 1
   },
   "CritSkillBoost": {
      "Clan Ship": 1,
      "Shadow Clone": 1,
      "Heavenly Strike": 1,
      "Pet": 1,
      "Dagger": 1,
      "Gold Gun": 1,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "ForbiddenContract": {
      "Clan Ship": 1,
      "Shadow Clone": 1,
      "Heavenly Strike": 1,
      "Pet": 1,
      "Dagger": 1,
      "Gold Gun": 1,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "ShadowCloneMultiCastSkill": {
      "Clan Ship": 0,
      "Shadow Clone": 1,
      "Heavenly Strike": 0,
      "Pet": 0,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "PuppetMaster": {
      "Clan Ship": 0,
      "Shadow Clone": 1,
      "Heavenly Strike": 0,
      "Pet": 0,
      "Dagger": 0,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "TerrifyingPact": {
      "Clan Ship": null,
      "Shadow Clone": null,
      "Heavenly Strike": null,
      "Pet": null,
      "Dagger": null,
      "Gold Gun": null,
      "Fairy": 1,
      "HoG": 1,
      "Chesterson": 1
   },
   "OfflineGold": {
      "Clan Ship": null,
      "Shadow Clone": null,
      "Heavenly Strike": null,
      "Pet": null,
      "Dagger": null,
      "Gold Gun": null,
      "Fairy": 1,
      "HoG": 1,
      "Chesterson": 1
   },
   "CritSkillBoostDmg": {
      "Clan Ship": 0.5,
      "Shadow Clone": 0.6,
      "Heavenly Strike": 0,
      "Pet": 0.7,
      "Dagger": 0.75,
      "Gold Gun": 0.6,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "UltraDagger": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 0,
      "Dagger": 1,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "Cloaking": {
      "Clan Ship": null,
      "Shadow Clone": null,
      "Heavenly Strike": null,
      "Pet": null,
      "Dagger": null,
      "Gold Gun": null,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "Backstab": {
      "Clan Ship": 1,
      "Shadow Clone": 1,
      "Heavenly Strike": 0,
      "Pet": 1,
      "Dagger": 1,
      "Gold Gun": 1,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "PoisonedBlade": {
      "Clan Ship": 1,
      "Shadow Clone": 1,
      "Heavenly Strike": 1,
      "Pet": 1,
      "Dagger": 1,
      "Gold Gun": 1,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "MultiMonsters": {
      "Clan Ship": null,
      "Shadow Clone": null,
      "Heavenly Strike": null,
      "Pet": null,
      "Dagger": null,
      "Gold Gun": null,
      "Fairy": 0,
      "HoG": 0,
      "Chesterson": 1
   },
   "GuidedBlade": {
      "Clan Ship": 0.5,
      "Shadow Clone": 0.6,
      "Heavenly Strike": 0,
      "Pet": 0.7,
      "Dagger": 0.75,
      "Gold Gun": 0.6,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "CriticalHit": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 0,
      "Dagger": 1,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "LoadedDice": {
      "Clan Ship": null,
      "Shadow Clone": null,
      "Heavenly Strike": null,
      "Pet": null,
      "Dagger": null,
      "Gold Gun": null,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "StreamOfBladesMultiCastSkill": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 0,
      "Dagger": 1,
      "Gold Gun": 0,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "QuickFortune": {
      "Clan Ship": null,
      "Shadow Clone": null,
      "Heavenly Strike": null,
      "Pet": null,
      "Dagger": null,
      "Gold Gun": null,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "Transmutation": {
      "Clan Ship": null,
      "Shadow Clone": null,
      "Heavenly Strike": null,
      "Pet": null,
      "Dagger": null,
      "Gold Gun": null,
      "Fairy": 1,
      "HoG": 1,
      "Chesterson": 1
   },
   "GoldGun": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 0,
      "Dagger": 0,
      "Gold Gun": 1,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "ChestGold": {
      "Clan Ship": null,
      "Shadow Clone": null,
      "Heavenly Strike": null,
      "Pet": null,
      "Dagger": null,
      "Gold Gun": null,
      "Fairy": 1,
      "HoG": 0,
      "Chesterson": 1
   },
   "MidasSkillBoost": {
      "Clan Ship": null,
      "Shadow Clone": null,
      "Heavenly Strike": null,
      "Pet": null,
      "Dagger": null,
      "Gold Gun": null,
      "Fairy": 0.6,
      "HoG": 0.6,
      "Chesterson": 1
   },
   "MagnumOpus": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 0,
      "Dagger": 0,
      "Gold Gun": 1,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "LovePotion": {
      "Clan Ship": null,
      "Shadow Clone": null,
      "Heavenly Strike": null,
      "Pet": null,
      "Dagger": null,
      "Gold Gun": null,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "HandOfMidasMultiCastSkillBoost": {
      "Clan Ship": null,
      "Shadow Clone": null,
      "Heavenly Strike": null,
      "Pet": null,
      "Dagger": null,
      "Gold Gun": null,
      "Fairy": 0.6,
      "HoG": 0.6,
      "Chesterson": 1
   },
   "AuricShot": {
      "Clan Ship": 0,
      "Shadow Clone": 0,
      "Heavenly Strike": 0,
      "Pet": 0,
      "Dagger": 0,
      "Gold Gun": 1,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "KratosSummon": {
      "Clan Ship": 1,
      "Shadow Clone": 1,
      "Heavenly Strike": 1,
      "Pet": 1,
      "Dagger": 1,
      "Gold Gun": 1,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "RoyalContract": {
      "Clan Ship": null,
      "Shadow Clone": null,
      "Heavenly Strike": null,
      "Pet": null,
      "Dagger": null,
      "Gold Gun": null,
      "Fairy": 1,
      "HoG": 1,
      "Chesterson": 1
   },
   "ExplosivesExpert": {
      "Clan Ship": null,
      "Shadow Clone": null,
      "Heavenly Strike": null,
      "Pet": null,
      "Dagger": null,
      "Gold Gun": null,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   },
   "PhilosophersFlux": {
      "Clan Ship": 1,
      "Shadow Clone": 1,
      "Heavenly Strike": 1,
      "Pet": 1,
      "Dagger": 1,
      "Gold Gun": 1,
      "Fairy": null,
      "HoG": null,
      "Chesterson": null
   }
}